# Generated by Django 5.0.10 on 2025-02-04 13:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Attachment')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description')),
                ('brief_description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('status', models.CharField(blank=True, default='pending', max_length=255, verbose_name='Status')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Comment')),
                ('visibility', models.BooleanField(blank=True, default=False, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created At')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click Count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='categories.category', verbose_name='Category')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
        ),
    ]
