# Generated by Django 5.0.10 on 2025-09-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_ai_enhancements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='articleversion',
            name='unique_article_version',
        ),
        migrations.AlterUniqueTogether(
            name='articleversion',
            unique_together={('article', 'version_number')},
        ),
    ]
