# Generated by Django 5.0.10 on 2025-09-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_fix_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='translation_status',
            field=models.CharField(choices=[('not_translated', 'Not Translated'), ('pending', 'Pending Translation'), ('translated', 'Translated'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_translated', max_length=20, verbose_name='Translation Status'),
        ),
    ]
