# Generated by Django 5.0.10 on 2025-09-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_translated',
            field=models.BooleanField(default=False, verbose_name='AI Translated'),
        ),
    ]
