# Generated by Django 5.0.10 on 2025-09-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_add_ai_translated_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='brief_description_arabic',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_translated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Translated At'),
        ),
        migrations.AddField(
            model_name='article',
            name='manually_edited',
            field=models.BooleanField(default=False, verbose_name='Manually Edited'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_arabic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_arabic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Arabic)'),
        ),
    ]
