# Generated by Django 5.0.10 on 2025-10-02 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_google_drive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('google_drive_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Drive File ID')),
                ('google_drive_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Drive Filename')),
                ('google_drive_web_view_link', models.URLField(blank=True, null=True, verbose_name='Google Drive Web View Link')),
                ('google_drive_web_content_link', models.URLField(blank=True, null=True, verbose_name='Google Drive Web Content Link')),
                ('google_drive_file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Google Drive File Size')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Extracted Text')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20, verbose_name='Status')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'PDF File',
                'verbose_name_plural': 'PDF Files',
                'ordering': ['-upload_date'],
            },
        ),
    ]
