# Generated by Django 5.0.10 on 2025-02-04 13:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Category Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='category_logos/', verbose_name='Category Logo')),
                ('type', models.CharField(choices=[('Main', 'Main'), ('Sub', 'Sub')], default='Main', max_length=10)),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Sub-Category Name')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Sub-Category Name')),
                ('status', models.CharField(blank=True, default='pending', max_length=255, verbose_name='Status')),
                ('visibility', models.BooleanField(blank=True, default=0, max_length=10, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created At')),
                ('departments', models.ManyToManyField(blank=True, related_name='categories', to='departments.department')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category', verbose_name='Parent Category')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
