# Generated by Django 5.0.10 on 2025-02-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=2000)),
                ('visibility', models.BooleanField(blank=True, default=0, max_length=10, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created At')),
            ],
        ),
    ]
