# Generated by Django 5.0.10 on 2025-04-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
