#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

>&2 echo 'Ensuring media directories exist...'
mkdir -p /app/kquires/media/category_logos
mkdir -p /app/kquires/media/article_images
mkdir -p /app/kquires/media/user_avatars

>&2 echo 'Setting up media directory permissions...'
chmod -R 755 /app/kquires/media

exec "$@"
